server:
  port: 8081

notification:
  mongo:
    uri: ${NOTIFICATION_MONGO_URI}

spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      auto-index-creation: true
